### ISSUE TITLE
Add data contributor profile information

### ISSUE THREAD

**Issue by byrnenick** [Typehuman/SSEMMI#26]

**Comment by peterdouglas** [comment]
[SSEMMI Contributor Profile.pdf](https://github.com/Typehuman/SSEMMI/files/6470560/SSEMMI.Contributor.Profile.pdf)

**Comment by peterdouglas** [comment]
Add Contributor Profile as in image above, however is to be above manage keys detail.

**Comment by peterdouglas** [comment]
Is ready for review. The only difference is that it is currently below keys, as they are going to use the keys more.

**Comment by scottveirs** [comment]
Looks good, currently like this for authenticated viewer...

<img width="1043" alt="Screen Shot 2022-11-01 at 4 02 20 PM" src="https://user-images.githubusercontent.com/14044595/199358719-744291a1-45e5-4559-b49e-915668a42173.png">

...so closing.
