### ISSUE TITLE
Change landing page text to broaden geographic domain

### ISSUE THREAD

**Issue by scottveirs** [Typehuman/SSEMMI#54]
Simple modification of existing text. Good first issue.

**Comment by scottveirs** [comment]
The [Acartia landing page](https://acartia.io/home) has a modal in the upper right corner containing text. As a public (unauthenticated) user, I want the text to be changed from "within the Salish Sea" to "within the Salish Sea and across coastal Cascadia" in order to accurately describe the geographic domain of the data cooperative.

**Comment by scottveirs** [comment]
Here's what the modal currently looks like (screen grab today):
<img width="489" alt="Screen Shot 2022-02-24 at 5 30 55 PM" src="https://user-images.githubusercontent.com/14044595/155636528-214a06f1-47ee-4c92-aa0c-e32dc0fc69b1.png">

**Comment by hnrywltn** [comment]
Hey scottveirs, still need help with this? I'd like to contribute

**Comment by scottveirs** [comment]
Sure, Henry! Feel free to try out the code. I can help if documentation needs adjusting. @peterdouglas may have time between PhD tasks down under to answer dev questions.

**Comment by scottveirs** [comment]
Also @hnrywltn -- if you zoom on from the default Acartia map, as a dev based in SF you may enjoy looking through the marine mammal observations in/near the Bay Area

<img width="789" alt="Screen Shot 2022-05-25 at 6 00 01 PM" src="https://user-images.githubusercontent.com/14044595/170393726-b1a608ea-a907-46de-9437-ef898283eeb1.png">
!

**Comment by scottveirs** [comment]
Transfered to forked repo [here](https://github.com/salish-sea/acartia/issues/10), so closing.
