### ISSUE TITLE
Make upload template link more visible

### ISSUE THREAD

**Issue by scottveirs** [Typehuman/SSEMMI#57]
As an authenticated user, I want to be able to easily understand how to download the template .csv file for uploading data to the cooperative.

Currently, the CSS doesn't make it very clear that the word "here" is a hypertext link that leads to the `acartia-import-template.csv` file. See this 10/31/2022 screenshot (in OSX/Chrome when authenticated as me): 

<img width="1790" alt="Screen Shot 2022-10-31 at 12 21 43 PM" src="https://user-images.githubusercontent.com/14044595/199092735-522c4ab6-d6b5-470d-b46e-57e17545610e.png">

**Comment by SO-HYBE** [comment]
I can help with that assign me please

**Comment by scottveirs** [comment]
Hi @SO-HYBE , thanks for offering to help! 

Please fork and submit a pull request if you have some success. You are also welcome to propose a solution here and we can discuss. And/or let us know here if you have any questions.

**Comment by scottveirs** [comment]
@SO-HYBE we are moving to a fork of this repo. Come join us! Here is a link to the new version of this issue, which I'll now close...

https://github.com/salish-sea/acartia/issues/7
